workflows:
  ios-capacitor:
    name: iOS – Capacitor (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: 16.0
      node: 20
      cocoapods: default
      # Keep your Apple API key in secure environment variables or a Team “group”
      vars:
        BUNDLE_ID: "com.example.myapp"     # <-- change this
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"                # Capacitor default
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(…)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(…)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(…)
      # Cache to speed up builds
      cache:
        cache_paths:
          - ~/.npm
          - ~/Library/Caches/CocoaPods
          - ios/App/Pods

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          xcodebuild -version
      - name: Install JS deps
        script: npm ci
      - name: Build web assets
        script: npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Install CocoaPods
        working_directory: ios/App
        script: pod install
      - name: Code signing (automatic via App Store Connect API key)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

